services:
  mysql:
    image: mysql:8.0
    container_name: cycure-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cycure_quiz
      MYSQL_USER: cycure_user
      MYSQL_PASSWORD: cycure_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
